OC\WebAgencyBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: OC\WebAgencyBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        content:
            type: text
        email:
            type: string
            length: 255
        postId:
            type: integer
        isSeen:
            type: boolean
        date:
            type: datetime
    lifecycleCallbacks: {  }
