admin_comment_index:
    path:     /
    defaults: { _controller: "OCWebAgencyBundle:Comment:index" }
    methods:  GET

admin_comment_show:
    path:     /{id}/show
    defaults: { _controller: "OCWebAgencyBundle:Comment:show" }
    methods:  GET

admin_comment_new:
    path:     /new
    defaults: { _controller: "OCWebAgencyBundle:Comment:new" }
    methods:  [GET, POST]

admin_comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCWebAgencyBundle:Comment:edit" }
    methods:  [GET, POST]

admin_comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCWebAgencyBundle:Comment:delete" }
    methods:  DELETE
